### ISSUE TITLE
Password with angle brackets

### ISSUE THREAD

**Issue by maxmopp** [nthdimtech/signet-client#104]
I use generated passwords from keepassx and some of them contain <>
Signet message: "Signet cannot type this data. It contains characters not present in your keyboard layout" 
and suggests to copy the data which get into buffer like  "username : pas>sword"
Any chance to fix that?
Thanks
Max

**Comment by nthdimtech** [comment]
Signet is supposed to be okay with "<>" characters. This sounds like a
problem with your keyboard layout detection. What layout are you using?
If you go to "File->Settings->Reconfigure keyboard layout" what do you
see? A predefined set of keyboard layouts to handle the common cases is
one thing that could fix automatic detection bugs but I would like to
see if the automatic detection can be made to work better.

**Comment by maxmopp** [comment]
Ok, I had looked and checked but not close enough: I use a German /Austrian layout which seems for the most part correctly detected. There are two things sticking out:
- left of the y/shiftY the </> are missing
- right of the +/* is another #/' which is in fact the Enter

I did only a quick check with the R-Alt:
- left of y/Y | is missing
- right of +/* ’  (wrong, Enter)

Shift +  R-Alt:
-  left of y/Y no character (correct)
- right of +/* ` (wrong, Enter)

**Comment by nthdimtech** [comment]
Thankfully, the problem with the key left of "y" is simple. I forgot to add that key to the my scancode table so it isn't getting tested. I just pushed a fix, see commit decf71b.

I'd like to know more about the problem with the key to the right of "+/*". I'm actually not seeing this key on the German keyboard layout images I have seen online. What is the configuration producing and what are you expecting?

I'm closing this bug though since the angle brackets problem seems to solved. I can open up another issue if the apparent incorrect character is creating a different real problem. It could be simply that the scancode associated with that position on your keyboard isn't in the same place in my visualization.

**Comment by maxmopp** [comment]
Thanks a lot- I am away from home right now, will try to compile in the next couple of days.
The "+/*" key is not a problem: this key is just duplicated

**Comment by maxmopp** [comment]
Thanks a lot- I am away from home right now, will try to compile in the next couple of days.
The "+/*" key is not a problem: this key is just duplicated
