### ISSUE TITLE
Signet not detected via USB 3.0 port hub

### ISSUE THREAD

**Issue by Dennis1000** [nthdimtech/signet-client#117]
If the Signet device is plugged in directly in a Windows 10 PC usb 3.0 port it works, but using a USB 3.0 hub (this one https://www.amazon.com/dp/B019E6YVXC) it isn't detected (all other devices working)

**Comment by nthdimtech** [comment]
Sorry for the long delay on this. This kind of problem can be due to a lot of sources. Generally speaking it's usually a combination of how tight the fit is in the port and how contaminated the contacts are on the device. If blowing the dust out doesn't work you can clean the contacts with a thin brush and rubbing alchohol (Isopropyl alcohol).

One theory I have as to why Signet has more connection problems than some devices is that its USB port doesn't have raised contacts like many do and this results in a looser fit in the port. In any case I think software problems can be safely ruled out so I'm going to close this out.
