### ISSUE TITLE
No login with signet-0.9.13.4

### ISSUE THREAD

**Issue by maxmopp** [nthdimtech/signet-client#127]
Version signet-0.9.12.2 works as expected via context menu: fills username, password or logs in, albeit not via buttons (client jumps to beginning of list)

Version signet-0.9.13.4 does not work, neither context menu nor buttons, client jumps to beginning of list

Ubuntu 18.04.2 LTS

**Comment by nthdimtech** [comment]
I just tried the buttons and the context menu on 0.9.13.4 on my Linux system but it's not Ubuntu. My guess is that this is OS/Distro specific. Do you have another distro to try on or a Windows or MacOS computer to try on? That could rule out anything about your device/data. Also what is your firmware version? You can see it in the about dialog.

**Comment by maxmopp** [comment]
Device firmware is 1.3.4
I run xfce4 - I will try on a windows vm tomorrow

**Comment by nthdimtech** [comment]
Another option is to build the client from source: https://www.nthdimtech.com/signet/guides/how-to-build-the-client-from-source/

Some distro-specific issues go away when the client is built natively

**Comment by maxmopp** [comment]
Ok - tried on W10 on virtualbox: Client works as expected

**Comment by nthdimtech** [comment]
Sorry for the long delay, got distracted. So the virtualbox test tells us that it isn't anything to do with your device or device contents. If you don't have the time to build from source there are some simpler things you could try that might help me narrow down the problem.

1) Can you load a backup file from "file->open" and access your data that way?
2) Can you click the "copy" button instead of the type button to get a username or password?
3) If you open an account do either the copy or type buttons work as expected there?

**Comment by maxmopp** [comment]
I was distracted as well now :), sorry for the delay.
I tried 
1. will thry the export (backup) and import later
2. Yes, copy copies the username, but jumps to the beginning of the accounts list, I have to search again and can copy the pwd and i/f jumps to the beginning of the accounts list again
3. Copy Buttons from the opened account work as expected

**Comment by nthdimtech** [comment]
Just to clarify on (1) I didn't mean for you to use the import feature. I just meant "file->open" which allows you to access a backup's data in a read-only mode but doesn't affect the device or anything else.

For (2) the jumping to the start part is expected behavior. This is a problem I've had a hard time solving from an ease of use standpoint. At one point I chose the default policy to be to deselect an account after accessing a field from the main window to make it easy to select a different account later. I did this because I found it jarring at times to come back to the client and see an account still selected that I used maybe several hours ago. That said the deselection behavior may be too unintuitive to justify and I may remove it in the next release.

Could you give me some clarification of the original problem other than the deselection issue?  What stage of the login process failed? Does the device not light up when you press the login button? Does it not type you when you press the button, or is it something else?

**Comment by maxmopp** [comment]
Open sdb:
- <right click> copy username copies, but I have to paste, signet window minimizes, after unminimizing search results gets cleared, cursor jumps to top of the list - useable but signet window should not minimize
- copy button does the same

Open signet stick
- type username does nothing to the browser, search results gets cleared, cursor jumps to top of the list. If accidentially the last window was a notepad - username gets written to the notepad
- <right click> copy username copies, signet window stays visible, search results gets cleared, cursor jumps to top of the list

If I get some time I will try to compile from source

**Comment by maxmopp** [comment]
Tried to build on Ubuntu 18.04.2 LTS, installed build dependencies,   libgl-dev and libgl1-mesa-dev, ended with /usr/bin/ld: cannot find -lGL

**Comment by maxmopp** [comment]
Tried again and succeeded. Login does now work as expected. Sorry for the inconvenience

**Comment by nthdimtech** [comment]
Do you mean that you retried using the login feature on the released client or that you rebuilt from source successfully and then the login feature started working?

**Comment by maxmopp** [comment]
Both- but I deleted .cache/sessions and xfce4 first. Seems to have been a local issue. Thanks a lot

**Comment by nthdimtech** [comment]
I see, glad everything is working for you now. I will consider your feedback regarding minimization and auto-deselection. They are supposed to make things more efficient for the login case but I have also been bothered by them from time to time. I think will either remove or apply these behaviors to more specific cases like login only. The browser plugins offer the fastest flow right now so keyboard entry could take a small hit for the sake of simplicity.

**Comment by maxmopp** [comment]
Thanks, sounds great. Looking forward to the next version.
