### ISSUE TITLE
Github release / tag for v. 0.9.14?

### ISSUE THREAD

**Issue by Necklaces** [nthdimtech/signet-client#145]
Hey, I see there's no release / tag here on github for v. 0.9.14, any plans to make a release or no?

**Comment by nthdimtech** [comment]
I think you meant for 0.9.15. There is now a 0.9.15 release on the downloads page but I still need to add some of the auxiliary files such as file signatures and the source tarball. The 0.9.15 release fixes a small number of bugs. The only new feature is Signet HC support.

**Comment by Necklaces** [comment]
No I meant for 0.9.14, but now we need one for 0.9.15. Can't find them here:

- https://github.com/nthdimtech/signet-client/releases
- https://github.com/nthdimtech/signet-client/tags

**Comment by nthdimtech** [comment]
Oh I must have created the 0.9.14 locally and not pushed it, will fix soon. The 0.9.15 client needs release notes which I haven't written yet. I'll add its tag when I add the notes. I was a bit rushed getting 0.9.15 online since a Signet HC beta tester needed it ASAP.

On February 10, 2020 11:04:28 PM PST, Nichlas Severinsen <notifications@github.com> wrote:
>No I meant for 0.9.14, but now we need one for 0.9.15. Not to be found
>here:
>
>- https://github.com/nthdimtech/signet-client/releases
>- https://github.com/nthdimtech/signet-client/tags
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-client/issues/145#issuecomment-584501856

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nthdimtech** [comment]
Done and done, thanks for the tip
