### ISSUE TITLE
Allow generic fields to be added without requiring a "+" button press 

### ISSUE THREAD

**Issue by dragon788** [nthdimtech/signet-client#50]
I added a new entry today and all the fields from the top portion of the screen automatically saved, but the custom text I entered at the bottom didn't automatically save, I saved the entry and came back and noticed it was missing and then had to re-enter it and click the + to "add" it and then Save again.

This flow might make sense if you are editing an entry so if you make an unwanted change you can exit without applying, but I feel the first time you are adding an entry you would probably want any information put into a field to be saved.

**Comment by nthdimtech** [comment]
I'm a little confused about what you're saying. There are two steps to creating a new field: first creating the field with the "+" button then actually saving a value in the field. I'm not seeing any cases were a field is created and the client wont recognize that value needs to be saved. If you've only named a field then there isn't anything to save yet.

That said I'm not happy the way generic fields are created. It should automatically create a field whenever you edit a field name rather than require clicking the "+" button. I think this is what you're getting at, it is just a little harder to do.

**Comment by dragon788** [comment]
Ahhh I think I missed the fact that the first entry is the name and then you have to assign a value still. I was expecting the type of 'text' to store the free form days but having a name or index makes a lot of sense for export/import purposes.

**Comment by nthdimtech** [comment]
Well I don't think I explained it anywhere except for maybe in one video. It should be more intuitive so I'm going to leave this bug open with a different title

**Comment by dragon788** [comment]
Thanks! That does make a lot more sense. I was kind of expecting that the text field was more like a "comment" or "notes" field since that is how LastPass treats it, but if you can give it arbitrary names for custom data mapping and data via base64 encoded files or whatever, it makes way more sense that you have to hit something after selecting a type and having entered a name.

**Comment by nthdimtech** [comment]
I just pushed a fix for this that makes it clear that a field is being created. See 946c6dd. Pressing enter creates the field and gives the newly created field input focus.

Since "Notes" text blocks are so common in other password managers I've decided to make a "Notes" field show up automatically. It would be a user/generic field under the hood and end up using no space if left empty. See issue #93
