### ISSUE TITLE
Client URL field doesn't fill out completely in browser

### ISSUE THREAD

**Issue by mingzen** [nthdimtech/signet-client#59]
In Windows:

URL in the account browser field is:

`
http:<URL field here>
`

The printed URL fails if the URL field fails to include "http://"

The printed URL is also consistently only a portion of the URL in the account field when pressing from the main menu. Opening the account and then going to the URL will fill out the http:<URL field here>. Opening the account, closing the account, then clicking on the browse website button on the main page will print http:<URL field here>.

Examples:
www.github.com->http:www.github.com
patreon.com->http:patreon
paypal.com->http:paypal.com
facebook.com->http:faceboo
earthbaby.deliverybizpro.com->http:earthbaby

**Comment by nthdimtech** [comment]
I gave you an early release of the device before the campaign ended. A bug was fixed in the firmware since then that I believe will clear up this issue. Download the latest firmware [here ](http://nthdimtech.com/downloads/signet-releases/firmware/signet-1.2.4.sfw) and update it under "Device -> Update firmware" and let me know if the problem goes away.

**Comment by mingzen** [comment]
I've updated the firmware and URL field types correctly.
