### ISSUE TITLE
Signet dekstop client installer and window size persistence

### ISSUE THREAD

**Issue by izghitu** [nthdimtech/signet-client#71]
Hi,

I am a new signet Windows user and there are 2 things that make its use uncomfortable. The first one is that there's no signet desktop client installer, just an exe. It would be nice to have it packed in a .msi or .exe installer for windows and perhaps RPM/DEB packages for other Linux distros.

The second problem is that each time I open the signet desktop client it defaults to a screen position and window size and I have to re-size it each time.

Are there any plans to implement the above changes?

Thanks in advance.

**Comment by nthdimtech** [comment]
I do have plans to create at least a DEB package for Signet.

I'm not sure what role a Windows installer would play since Signet doesn't integrate with Windows in any way. An installer would just be a utility to copy the EXE somewhere which a user can already do with just a simple file. I'm sure there are some advantages but I'll probably not pursue it right away.

You make a good point about the initial windows size and position. I'll open up a separate issue for that.

**Comment by nthdimtech** [comment]
See issue #72 for Window size and position. I think it will be pretty simple so I'll try to get this into the next release.

**Comment by izghitu** [comment]
Thanks!
