### ISSUE TITLE
Import from keepass

### ISSUE THREAD

**Issue by maxmopp** [nthdimtech/signet-client#85]
KeePass CSV (1.x)
KeePass KBDX (2.x)
KeePass KBDX (2.34, Old Format)
all crash after first entry: Segmentation fault (core dumped)
this renders the device useless for me

**Comment by nthdimtech** [comment]
I know some people have used this feature successfully before so we just need to figure out what's different about your case. What client version are you using? Also when you say that they crash after the first entry do you mean that you see a prompt to insert a correctly decrypted entry and it crashes when you confirm it?

**Comment by nthdimtech** [comment]
I've managed to replicate the issue and create a fix. I'll push it after I do a bit more validation. The issue was introduced in 0.9.11 and I will have a fix in 0.9.12. If you want to import your KeePass database before the next release you can simply run 0.9.10 to import the database then use 0.9.11 afterwards. You can find 0.9.10 here: https://nthdimtech.com/downloads/signet-releases/0.9.10/

**Comment by nthdimtech** [comment]
I've pushed the fix. If you don't want to build it you can run the 0.9.10 client to import or wait for the 0.9.12 release. Sorry for the trouble.

**Comment by timetoseek** [comment]
Update:  I have the same issue of the Windows (64 bit) client 0.9.11 crashing during import of records from Keepass (version 2.39.1).   As per your suggestion, I used version 0.9.10, and the import worked.  The one drawback is that we are required to press the blue button for every single record we wish to import.  A bit inconvenient, especially for those of us with a lot of records!  In any case, it is an acceptable workaround, until version 0.9.12 is deployed.
