### ISSUE TITLE
Database backup prompt before Signet device is plugged in

### ISSUE THREAD

**Issue by izghitu** [nthdimtech/signet-client#87]
Hi,

Since the last update to Desktop client 0.9.11 on my Windows PC, when it's time for backups(auto-weekly) each time the Signet desktop client opens and the device is not yet plugged in I am being prompted to perform the database backup. Obviously it won't work because I did not yet plug in the USB stick and did not enter the password. So I have to close the auto-backup window prompt, plugin the device, enter the password then manually run the backup procedure.

This did not happen in version 0.9.10 just thought it's annoying and would require fixing at some point in time.

Thanks

**Comment by nthdimtech** [comment]
This seems to be a side effect of the settings file being loaded at window creation time instead of at login time. This was done so that the window size/position can be retained across sessions. I just need to pull the automatic backup check out of the settings load and into the login setup function.

**Comment by nthdimtech** [comment]
Just tested a fix for this and pushed it.  See a1a93ac
