### ISSUE TITLE
(Password Slots) Repeated characters get mangled if mixed-case

### ISSUE THREAD

**Issue by greenhelper** [nthdimtech/signet-client#90]
Hi,

It's a bit hard to describe what's going on. 
Essentially, a character vanishes if the same characters appears at least twice and if it is mixed case.

Maybe examples clear it up a bit: 
(the first line is always what is stored in the password slot, the second line is what gets actually typed when pressing the appropriate button). 

79HwdzD2ebOtLDd4x
79HwdzD2ebOtLD4x
(notice the d at the end is missing) 

Dd
D

dD
d

dDdd
dd

dDDddd
dDdd

dDDdddd
dDddd

Tested on Win10, Ubuntu 16.04, Signet firmware 1.3.2, client 0.9.11.

**Comment by greenhelper** [comment]
Additionally, in case you are wondering, 4 "d"s work just fine!

dddd
dddd

DDDD
DDDD

**Comment by nthdimtech** [comment]
Thanks for the detailed notes. I figured it out. The password slots feature works by storing scancode/modifier pairs (to not burden the firmware with translation from unicode). It turns out you need to insert a depress between presses that share the same scancode but different modifiers. I just pushed a fix and tried most of your examples and got correct results.

I was worried this would require a firmware update but the scancode/modifier data is generated by the client. If you build the latest client and enter the affected passwords again they should type correctly.
