### ISSUE TITLE
Windows Desktop client not keeping windows size/position

### ISSUE THREAD

**Issue by izghitu** [nthdimtech/signet-client#95]
Hi,

Since the last update the windows desktop client is keeping the windows size/position, thanks for that. There's one issue however. Since I connected a second monitor to my laptop the application no longer seems to keep its position/size. Each time it goes to systray and then is called back with the push of the button it defaults to its initial size/position.

This happens on both screens. It starts working fine as soon as I unplug the second monitor.

**Comment by nthdimtech** [comment]
I have been trying to reproduce this with the latest build with no luck. What OS are/were you running. The latest version uses a newer version of Qt and it's possible it could fix it. There may not be much I can do easily within the application because it doesn't do any windows position management, it just unhides the window and the position is supposed to be the same.

**Comment by izghitu** [comment]
With the update to the latest version the issue got fixed. Perhaps there was a corruption of some kind of the Qt settings, I am not sure and there's no way to tell.

Thanks!
