### ISSUE TITLE
Allow "user data" fields to be of type "secret" which masks the data behind a hide/unhide button

### ISSUE THREAD

**Issue by espoelstra** [nthdimtech/signet-client#99]
I occasionally run into cases where I have a site that has a password and an additional secret like a user access token that wouldn't make sense to store in a separate "entry" in the database, but rather as an additional "secret" field in the site entry.

**Comment by nthdimtech** [comment]
I like this idea. I've implemented this by adding a new "Text (Secret)" option when creating a new generic field. If you create a generic field with this option it will have a "Hide" checkbox and it will be hidden by default. I tested a number of cases and pushed to master.

Since I didn't want to change the internal data structures right away this is implemented internally by storing the field name with a "." prefix to denote that it is a secret field. The GUI code strips the "." prefix when displaying the name. As a consequence of this approach if a user named a field ".myfield" it would automatically become secret. Arguably a bug but also arguably an obscure feature...
